### PR TITLE
Fix characteristics monitoring cancelling

### LINKED ISSUE #280: Operations on publishers should be atomic
Operations on publishers should be atomic, since a new publisher might be attached at the same time as a new value is published.

_Originally posted by @mikolak in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzAxNzUyNzM0/pull_request_reviews/more_threads_

### PR DESCRIPTION
**Pull request by bartoszwilk**
Resolves https://github.com/Polidea/FlutterBleLib/issues/280

### CODE REVIEW

File: lib/internal/simulation_manager_mixins/characteristics_mixin.dart [hunk 1]
```diff
@@ -222,25 +227,28 @@ mixin CharacteristicsMixin on SimulationManagerBaseWithErrorChecks {
...
+                    targetCharacteristic.id, e, transactionId);
+
+                await _monitoringSubscriptions[transactionId]
+                    ?.subscription
+                    ?.cancel();
+                _monitoringSubscriptions.remove(transactionId);
+              }
+            }, onError: (error) {
+              _bridge.publishCharacteristicMonitoringError(
+                  targetCharacteristic.id, error, transactionId);
```
Comment (mikolak) [inline lib/internal/simulation_manager_mixins/characteristics_mixin.dart]: targetCharacteristic.id seems obsolete

**Comment by pawelByszewski** [comment]
What about writing some unit tests?

**Review by mikolak — APPROVED** [review]
