### PR TITLE
Fix NPE when using lower case for defining UUIDs of services/characteristics

### LINKED ISSUE #66: PlatformException when calling service.characteristics() with SimulatedCharacteristic
```
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
D/com.polidea.flutter_ble_lib.FlutterBleLibPlugin(28778): on native side observed method: characteristicsForService
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
E/MethodChannel#flutter_ble_lib(28778): Failed to handle method call
E/MethodChannel#flutter_ble_lib(28778): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.blemulator.SimulatedAdapter.getCharacteristicsForService(SimulatedAdapter.java:328)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.getCharacteristicsForService(DiscoveryDelegate.java:152)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.onMethodCall(DiscoveryDelegate.java:72)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.FlutterBleLibPlugin.onMethodCall(FlutterBleLibPlugin.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_ble_lib(28778): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter_ble_lib(28778): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/com.polidea.flutter_ble_lib.FlutterBleLibPlugin(28778): on native side observed method: characteristicsForService
I/SimulatedAdapter(28778): discoverAllServicesAndCharacteristicsForDevice
E/MethodChannel#flutter_ble_lib(28778): Failed to handle method call
E/MethodChannel#flutter_ble_lib(28778): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.blemulator.SimulatedAdapter.getCharacteristicsForService(SimulatedAdapter.java:328)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.getCharacteristicsForService(DiscoveryDelegate.java:152)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.onMethodCall(DiscoveryDelegate.java:72)
E/MethodChannel#flutter_ble_lib(28778): 	at com.polidea.flutter_ble_lib.FlutterBleLibPlugin.onMethodCall(FlutterBleLibPlugin.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_ble_lib(28778): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_ble_lib(28778): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_ble_lib(28778): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter_ble_lib(28778): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter_ble_lib(28778): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/gioteas.tefori(28778): Waiting for a blocking GC ProfileSaver
I/gioteas.tefori(28778): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 12.000ms
```

### PR DESCRIPTION
**Pull request by mikolak**
Fixes #66 

Issue was caused by using case specified by the user to store data in the map, instead of readjusting it to one format.

### CODE REVIEW

File: android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java [hunk 1]
```diff
@@ -324,7 +324,7 @@ public void onSuccess(DeviceContainer deviceContainer) {
                     if (service.getId() == serviceIdentifier) {
                         return deviceContainer
                                 .getCharacteristics()
-                                .get(service.getUuid().toString().toUpperCase())
+                                .get(service.getUuid().toString().toUpperCase()) //HERE; TODO remove mark
```
Comment (bartoszwilk) [inline android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java]: Is it on purpose or you forgot to commit the fix?

**Review by bartoszwilk — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java (hunk 1 above)
Comment (mikolak) [reply android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java]: Forgot to remove the comment from analysis. Fix is in DartMethodCaller.

Comment (mikolak) [reply android/src/main/java/com/polidea/blemulator/SimulatedAdapter.java]: Forgot to remove the comment from analysis. Fix is in DartMethodCaller.

**Review by bartoszwilk — APPROVED** [review]
